src/WebDjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

from rest_framework_simplejwt.views import (
    TokenObtainPairView, 
    TokenRefreshView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False)),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/feed/urls.py
from django.urls import path
from .views import (TicketCreateView, TicketUpdateView,
                    TicketDeleteView, ReviewCreateView, ReviewUpdateView,
                    ReviewDeleteView, UserFollowsCreateView, unfollowView,
                    add_follow, FeedView, TicketDetailView, CreateTicketAndReviewView, PostsListView)


app_name = 'feed'

urlpatterns = [
    path('posts', PostsListView.as_view(), name='posts'),
    path('add_ticket_and_review/', CreateTicketAndReviewView.as_view(), name='add_ticket_and_review'),
    path('feed/', FeedView.as_view(), name='feed'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('add_follow/', add_follow, name='add_follow'),
    path('add_ticket/', TicketCreateView.as_view(), name='add_ticket'),
    path('edit_ticket/<int:pk>/', TicketUpdateView.as_view(), name='edit_ticket'),
    path('delete_ticket/<int:pk>/', TicketDeleteView.as_view(), name='delete_ticket'),
    path('add_review/<int:pk>/', ReviewCreateView.as_view(), name='add_review'),
    path('edit_review/<int:pk>/', ReviewUpdateView.as_view(), name='edit_review'),
    path('delete_review/<int:pk>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('follows/', UserFollowsCreateView.as_view(), name='follow_list'),
    path('unfollow/<int:pk>/', unfollowView.as_view(), name='unfollow'),
]

src/feed/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor.fields import RichTextField


class Ticket(models.Model):
    """Model for a ticket."""
    title = models.CharField(max_length=128, help_text='Titre du billet')
    author = models.CharField(max_length=128, default='Auteur inconnu', help_text='Auteur du livre')
    description = RichTextField(max_length=2048, blank=True, help_text='Description du livre')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    """Model for a review."""
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text='Note attribuée au livre'
    )
    headline = models.CharField(max_length=128, help_text='Titre de la critique')
    body = models.TextField(max_length=8192, blank=True, help_text='Contenu de la critique')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    """Model for a user following another user."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        unique_together = ('user', 'followed_user')

src/feed/forms.py
# feed/forms.py

from django import forms
from django.contrib.auth import get_user_model
from .models import Review, Ticket
from ckeditor.widgets import CKEditorWidget

User = get_user_model()


class TicketForm(forms.ModelForm):
    """Form for adding a tucket"""
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Ticket
        fields = ['title', 'author', 'description', 'image']


class UserFollowForm(forms.Form):
    username = forms.CharField(label='Nom d\'utilisateur', max_length=150,
                               widget=forms.TextInput(attrs={'placeholder': 'Nom d\'utilisateur'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("Cet utilisateur n'existe pas.")
        return username


class ReviewForm(forms.ModelForm):
    """Form for adding a review to a ticket."""
    rating = forms.ChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
        widget=forms.RadioSelect,
        label="Rating"
    )
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Review
        fields = ['headline', 'rating', 'body']

src/feed/views.py
# feed/views.py
from django.db.models import Q, Prefetch, Count, Value, CharField, F
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse, reverse_lazy
from .models import Ticket, Review, UserFollows
from .forms import UserFollowForm, ReviewForm, TicketForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from itertools import chain


User = get_user_model()


class CreateTicketAndReviewView(LoginRequiredMixin, CreateView):
    """View for creating a ticket and a review."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/create_ticket_and_review.html'

    def form_valid(self, form):
        # Assigner l'utilisateur avant de sauvegarder le formulaire du billet
        form.instance.user = self.request.user
        response = super().form_valid(form)
        # Traiter le formulaire de critique si le billet est validement créé
        review_form = ReviewForm(self.request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.ticket = self.object  # Le nouveau billet créé
            review.user = self.request.user
            review.save()
        return response

    def get_success_url(self):
        """Return the URL to redirect to after creating a ticket and a review."""
        return reverse('feed:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'review_form' not in context:
            context['review_form'] = ReviewForm(self.request.POST or None)
        return context


class TicketDetailView(LoginRequiredMixin, DetailView):
    """View for see a single ticket with all the reviews."""
    model = Ticket
    template_name = 'feed/ticket_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = self.object.review_set.all().order_by('-time_created')
        context['stars'] = range(1, 6)
        return context


class FeedView(LoginRequiredMixin, ListView):
    """View for the feed."""
    template_name = 'feed/feed.html'
    context_object_name = 'feed_items'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        followed_users = UserFollows.objects.filter(user=user).values_list('followed_user', flat=True)
        recent_reviews_prefetch = Prefetch(
            'review_set',
            queryset=Review.objects.order_by('-time_created')[:2],
            to_attr='recent_reviews'
        )
        tickets = Ticket.objects.filter(
            Q(user__in=followed_users) | Q(user=user)
        ).prefetch_related(recent_reviews_prefetch).annotate(num_reviews=Count('review')).order_by('-time_created')
        return tickets

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stars'] = range(1, 6)
        return context


@login_required
def add_follow(request):
    """add a follow."""
    if request.method == 'POST':
        form = UserFollowForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                followed_user = User.objects.get(username=username)
                if UserFollows.objects.filter(user=request.user, followed_user=followed_user).exists():
                    form.add_error(None, 'Vous suivez déjà cet utilisateur.')
                else:
                    UserFollows.objects.create(user=request.user, followed_user=followed_user)
                    return redirect('feed:follow_list')
            except User.DoesNotExist:
                form.add_error('username', 'Cet utilisateur n\'existe pas.')
    else:
        form = UserFollowForm()
    return render(request, 'feed/add_follow.html', {'form': form})


class UserFollowsCreateView(LoginRequiredMixin, ListView):
    """View for following a user."""
    model = UserFollows
    template_name = 'feed/user_follows.html'
    context_object_name = 'follows'

    def get_queryset(self):
        return UserFollows.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserFollowForm()
        context['followers'] = UserFollows.objects.filter(followed_user=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        form = UserFollowForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                followed_user = User.objects.get(username=username)
                if UserFollows.objects.filter(user=request.user, followed_user=followed_user).exists():
                    messages.error(request, 'Vous suivez déjà cet utilisateur.')
                else:
                    UserFollows.objects.create(user=request.user, followed_user=followed_user)
                    messages.success(request, 'Utilisateur suivi avec succès.')
                    return redirect('feed:follow_list')
            except User.DoesNotExist:
                messages.error(request, 'Cet utilisateur n\'existe pas.')
        else:
            # Gestion des erreurs du formulaire
            for error in form.errors.values():
                messages.error(request, error.as_text())
        return super().get(request, *args, **kwargs)  # Rediriger vers la même page avec les messages d'erreur.


class unfollowView(LoginRequiredMixin, DeleteView):
    model = UserFollows
    success_url = reverse_lazy('feed:follow_list')

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """View for creating a review."""
    model = Review
    form_class = ReviewForm
    template_name = 'feed/review_create_form.html'

    def form_valid(self, form):
        # Vérification pour éviter la duplication de critique pour le même ticket par le même utilisateur
        self.ticket = get_object_or_404(Ticket, pk=self.kwargs.get('pk'))
        existing_review = Review.objects.filter(ticket=self.ticket, user=self.request.user).exists()
        if existing_review:
            form.add_error(None, 'Vous avez déjà publié une critique pour ce billet.')
            form.add_error(None, 'Cliquez pour retourner au flux.')
            return self.form_invalid(form)

        form.instance.user = self.request.user
        form.instance.ticket = self.ticket
        return super().form_valid(form)

    def get_success_url(self):
        """Return the URL to redirect to after creating a review."""
        return reverse('feed:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket'] = get_object_or_404(Ticket, pk=self.kwargs.get('pk'))
        return context


class ReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """View for updating a review"""
    model = Review
    form_class = ReviewForm
    template_name = 'feed/review_update_form.html'

    def test_func(self):
        # Récupère l'objet review en cours de modification
        review = self.get_object()
        # Vérifie que l'utilisateur actuel est l'auteur de la critique
        return self.request.user == review.user

    def get_queryset(self):
        """Return the reviews of the current user."""
        return Review.objects.filter(user=self.request.user)

    def get_success_url(self):
        """Return the URL to redirect to after updating a review."""
        return reverse('feed:posts')


class ReviewDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View for deleting a review."""
    model = Review
    template_name = 'feed/review_confirm_delete.html'

    def test_func(self):
        # Récupère l'objet review en cours de modification
        review = self.get_object()
        # Vérifie que l'utilisateur actuel est l'auteur de la critique
        return self.request.user == review.user

    def get_queryset(self):
        """Return the reviews of the current user."""
        return Review.objects.filter(user=self.request.user)

    def get_success_url(self):
        """Return the URL to redirect to after deleting a review."""
        return reverse('feed:posts')


class TicketCreateView(LoginRequiredMixin, CreateView):
    """View for creating a ticket."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/ticket_create.html'
    success_url = reverse_lazy('feed:feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """View for updating a ticket."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/ticket_update_form.html'
    success_url = reverse_lazy('feed:posts')

    def test_func(self):
        ticket = self.get_object()
        return ticket.user == self.request.user


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View for deleting a ticket."""
    model = Ticket
    template_name = 'feed/ticket_confirm_delete.html'
    success_url = reverse_lazy('feed:posts')

    def test_func(self):
        ticket = self.get_object()
        return ticket.user == self.request.user


class PostsListView(LoginRequiredMixin, ListView):
    """View for listing tickets and reviews."""
    template_name = 'feed/posts_list.html'
    context_object_name = 'items'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user

src/feed/templates/feed/add_follow.html
<!-- feed/templates/feed/add_follow.html -->


<div class="container">
    <h1>Suivre d'autres utilisateurs</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
    <div class="text-dark">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
</div>

src/feed/templates/feed/create_ticket_and_review.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Créer un Billet et une Critique</h1>
    <form method="post" enctype="multipart/form-data" style="max-width: 600px;">
        {% csrf_token %}
        {{ form.media }}
        
        <div class="form-group">
            <label for="id_title">Titre</label>
            <input type="text" class="form-control" id="id_title" name="title" required>
            <small class="form-text text-muted">Inscrire le titre du livre dont vous demandez la critique.</small>
        </div>
        <div class="form-group">
            <label for="id_author">Auteur</label>
            <input type="text" class="form-control" id="id_author" name="author" required>
            <small class="form-text text-muted">Inscrire le nom de l'auteur du livre.</small>
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
            <small class="form-text text-muted">Résumez du livre dont vous voulez la critique.</small>
        </div>
        <div class="form-group">
            <label for="id_image">Image</label>
            <button type="button" class="btn btn-primary" onclick="document.getElementById('id_image').click();">
                Télécharger fichier
            </button>
            <input type="file" class="form-control" id="id_image" name="image" accept="image/*" style="display:none;">
            <small class="form-text text-muted" id="file-name"></small>
        </div>
        <hr>

        <h2>Critique associée</h2>
        <div class="form-group">
            {% for field in review_form %}
                {% if field.name == 'rating' %}
                    <label>{{ field.label }}</label>
                    {% for choice in field %}
                        <div class="form-check form-check-inline">
                            {{ choice.tag }}
                            <label class="form-check-label" for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
                        </div>
                    {% endfor %}
                {% else %}
                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            {% endfor %}
        </div>
        
        <button type="submit" class="btn btn-success">Publier le billet et la critique</button>
    </form>
</div>

<script>
    document.getElementById('id_image').onchange = function () {
        document.getElementById('file-name').textContent = this.files[0].name;
    };
</script>
{% endblock %}

src/feed/templates/feed/feed.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
<div>
    <a href="{% url 'feed:add_ticket' %}" class="btn btn-outline-primary">Demander une critique</a>
    <a href="{% url 'feed:add_ticket_and_review' %}" class="btn btn-outline-primary">Créer un Billet et une Critique</a>
</div> 
</br>

    <div class="list-group">
        {% for ticket in feed_items %}
        <div class="card mb-4" style="max-width: 700px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    {% if ticket.image %}
                    <a href="{% url 'feed:ticket_detail' ticket.id %}">
                        <img src="{{ ticket.image.url }}" class="card-img" alt="{{ ticket.title }}">
                    </a>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <em class="ticket-publication">
                            {% if ticket.user == request.user %}Vous avez{% else %}{{ ticket.user.username }} a{% endif %} publié un ticket
                        </em>
                        <p class="ticket-date">{{ ticket.time_created|date:"d M Y H:i" }}</p>
                        <a href="{% url 'feed:ticket_detail' ticket.id %}" style="text-decoration: none;">
                            <h5 class="ticket-title">{{ ticket.title }}</h5>
                        </a>
                        <h5 class="ticket-author">{{ ticket.author }}</h5>
                        <p class="description-title">Résumé</p>
                        <div id="shortDescription{{ forloop.counter }}" class="ticket-description">
                            {{ ticket.description|truncatechars:400|safe }}
                            {% if ticket.description|length > 400 %}
                            <a href="#" data-index="{{ forloop.counter }}" class="toggleDescription">Lire la suite</a>
                            {% endif %}
                        </div>
                        <div id="fullDescription{{ forloop.counter }}" class="ticket-description collapse">
                            {{ ticket.description|safe }}
                            <a href="#" data-index="{{ forloop.counter }}" class="toggleDescription">Réduire</a>
                        </div>
                        <div class="card-footer" style = "background-color: white;">
                            <a href="{% url 'feed:add_review' ticket.id %}" class="btn btn-dark">Ajouter une Critique</a>
                            <a href="{% url 'feed:ticket_detail' ticket.id %}" class="btn btn-outline-dark">Voir toutes les critiques ({{ ticket.num_reviews }})</a>
                        </div>
                    </div>
                </div>
            </div>
        </br>
            {% for review in ticket.recent_reviews %}
            <div class="card text-bg-light mb-3" style="max-width: 600px;margin-left: 30px;">
                <div class="card-header">{% if review.user == request.user %}Vous avez{% else %}{{ review.user.username }} a{% endif %} publié une critique | Date de publication : <strong>{{ review.time_created|date:"d M Y H:i" }}</strong></div>
                
                <div class="card-body">
                  <h5 class="card-title">{{ review.headline }}</h5>
                  <p class="card-text">Critique</p>
                  <p>
                <div id="shortReview{{ forloop.parentloop.counter }}{{ forloop.counter }}">{{ review.body|truncatechars:200|safe }}
                    {% if review.body|length > 200 %}
                    <a href="#" data-index="{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="toggleReview">Lire la suite...</a>
                    {% endif %}
                </div>
                <div id="fullReview{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="collapse">
                    {{ review.body|safe }}
                    <a href="#" data-index="{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="toggleReview">Réduire</a>
                </div>
            </p>
            <p>Note :</p>
            <div class="mt-2">
            {% for star in stars %}
            <i class="fa fa-star {% if review.rating >= star %}text-warning{% else %}text-muted{% endif %}"></i>
            {% endfor %}
            </div>
                </div>
                
                
              </div>
              
              {% endfor %}
              
        </div>
        
        {% empty %}
        <div class="alert alert-info" role="alert">
            Aucun billet ou commentaire à afficher.
        </div>
        {% endfor %}
        
        <!-- Pagination -->
        {% include 'feed/pagination.html' %}
    </div>
</div>
{% endblock %}

src/feed/templates/feed/review_create_form.html
{% extends 'base.html' %}

{% block content %}
</br>
<div class="container">
    <h1><span class="badge bg-dark">Créer une critique</span></h1>

</br>
    
        <div class="card mb-4" style="max-width: 700px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    {% if ticket.image %}
                    <img src="{{ ticket.image.url }}" class="card-img" alt="{{ ticket.title }}">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <em class="ticket-publication">
                            {{ ticket.user.username }} a besoin d'une critique pour : "{{ ticket.title }}"
                        </em>
                        <p class="ticket-date"><strong>{{ ticket.time_created|date:"d M Y H:i" }}</strong></p>
                        <h5 class="ticket-title">{{ ticket.title }}</h5>
                        <h5 class="ticket-author">{{ ticket.author }}</h5>
                        <p class="description-title">Résumé</p>
                        <div id="shortDescription{{ forloop.counter }}" class="ticket-description">
                            {{ ticket.description|truncatechars:400|safe }}
                            {% if ticket.description|length > 400 %}
                            <a href="#" data-index="{{ forloop.counter }}" class="toggleDescription">Lire la suite</a>
                            {% endif %}
                    </div>
                </div>
            </div>
    
            </div>
    </div>

    <form method="post" enctype="multipart/form-data" style="max-width: 600px;">
        {% csrf_token %}
        {{ form.media }}
        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                <a href="{% url 'feed:feed' %}"> {{ form.non_field_errors }}</a>
            </div>
           
        {% endif %}
        <div class="form-group">
            <label for="{{ form.headline.id_for_label }}">Titre de la critique :</label>
            <input type="text" class="form-control" id="id_headline" name="headline" required>
            <div class="form-text">Inscrire un titre pour votre critique.</div>
        </div>
    </br>
        <div class="form-group">
            <label>Évaluation :</label>
            {% for choice in form.rating %}
            <div class="form-check form-check-inline">
                {{ choice.tag }}
                <label class="form-check-label" for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
            </div>
            {% endfor %}
        </div>
    </br>

        <div class="form-group">
            <label for="{{ form.body.id_for_label }}">Corps de la critique :</label>
            {{ form.body }}
        </div>
    </br>
        
        <button type="submit" class="btn btn-dark">Publier la critique</button>
    </form>
</div>

{% endblock %}

src/feed/templates/feed/review_update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Modifier la critique</h1>
    <form method="post" enctype="multipart/form-data" style="max-width: 600px;">
        {% csrf_token %}
        {{ form.media }}
        <div class="form-group">
            <label for="{{ form.headline.id_for_label }}">Titre de la critique :</label>
            <input type="text" class="form-control" id="id_headline" name="headline" required>
            <div class="form-text">Inscrire un titre pour votre critique.</div>
        </div>
    </br>
        <div class="form-group">
            <label>Évaluation :</label>
            {% for choice in form.rating %}
            <div class="form-check form-check-inline">
                {{ choice.tag }}
                <label class="form-check-label" for="{{ choice.id_for_label }}">{{ choice.choice_label }}</label>
            </div>
            {% endfor %}
        </div>
    </br>

        <div class="form-group">
            <label for="{{ form.body.id_for_label }}">Corps de la critique :</label>
            {{ form.body }}
        </div>
        
        <button type="submit" class="btn btn-success">Publier la critique</button>
    </form>
</div>
{% endblock %}

src/feed/templates/feed/test.html
<div class="card-body">
    <em class="ticket-publication">
        {% if ticket.user == request.user %}Vous avez{% else %}{{ ticket.user.username }} a{% endif %} publié un ticket
    </em>
    <p class="ticket-date">{{ ticket.time_created|date:"d M Y H:i" }}</p>
    <h5 class="ticket-title">{{ ticket.title }}</h5>
    <h5 class="ticket-author">{{ ticket.author }}</h5>
    <p class="description-title">Résumé</p>
    <div id="shortDescription{{ forloop.counter }}" class="ticket-description">
        {{ ticket.description|truncatechars:400|safe }}
        {% if ticket.description|length > 400 %}
        <a href="#" data-index="{{ forloop.counter }}" class="toggleDescription">Lire la suite</a>
        {% endif %}
    </div>
    <div id="fullDescription{{ forloop.counter }}" class="ticket-description collapse">
        {{ ticket.description|safe }}
        <a href="#" data-index="{{ forloop.counter }}" class="toggleDescription">Réduire</a>
    </div>
    <div class="card-footer">
        <a href="{% url 'feed:add_review' ticket.id %}" class="btn btn-dark">Ajouter une Critique</a>
        <a href="{% url 'feed:ticket_detail' ticket.id %}" class="btn btn-outline-dark">Voir toutes les critiques ({{ ticket.num_reviews }})</a>
    </div>
</div>

src/feed/templates/feed/ticket_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Supprimer le Billet</h1>
    <p>Êtes-vous sûr de vouloir supprimer "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Supprimer</button>
        <a href="{% url 'feed:posts' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}

src/feed/templates/feed/ticket_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="create_ticket_title">Créer un ticket</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" style="max-width: 600px;"  novalidate>
        {% csrf_token %}
        {{ form.media }} <!-- Assurez-vous d'inclure les médias nécessaires pour CKEditor -->

        <div class="mb-2">
            <label for="{{ form.title.id_for_label }}" class="form-label">Titre</label>
            <input type="text" class="form-control" id="id_title" name="title" required>
            
            <div class="form-text">Inscrire le titre du livre dont vous demandez la critique.</div>
        </div>

        <div class="mb-3">
            <label for="{{ form.author.id_for_label }}" class="form-label">Auteur</label>
            <input type="text" class="form-control" id="id_author" name="author" required>
            <div class="form-text">Inscrire le nom de l'auteur du livre.</div>
        </div>

        <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
            {{ form.description }}
            <div class="form-text">Résumez du livre dont vous voulez la critique.</div>
        </div>

        <div class="mb-3">
            <label for="{{ form.image.id_for_label }}" class="form-label">Image</label>
            <input type="file" class="form-control" id="id_image" name="image" accept="image/*">
            <div class="form-text" id="file-name"></div>
        </div>

        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>

<script>
    document.getElementById('id_image').onchange = function () {
        document.getElementById('file-name').textContent = this.files[0].name;
    };
</script>
{% endblock %}

src/feed/templates/feed/userfollows_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Confirmer le désabonnement</h1>
    <p>Êtes-vous sûr de vouloir vous désabonner de {{ object.followed_user.username }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmer</button>
        <a href="{% url 'feed:follow_list' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>
{% endblock %}