src/WebDjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

from rest_framework_simplejwt.views import (
    TokenObtainPairView, 
    TokenRefreshView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False)),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path, include
from .views import signup, logout_view, login_view, ProfileDetailView, ProfileUpdateView, ProfileCreateView, ProfileApiViewSet, UserViewSet
from rest_framework.routers import DefaultRouter



app_name = 'accounts'

router = DefaultRouter()
router.register(r'profiles', ProfileApiViewSet, basename='profile')
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    path('', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('profile/', ProfileDetailView.as_view(), name='profile_detail'),  # Page de consultation du profil
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),  # Page de modification du profil
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('api/', include(router.urls)),
]

src/feed/urls.py
from django.urls import path
from .views import (TicketCreateView, TicketUpdateView,
                    TicketDeleteView, ReviewCreateView, ReviewUpdateView,
                    ReviewDeleteView, UserFollowsCreateView, unfollowView,
                    add_follow, FeedView, TicketDetailView, CreateTicketAndReviewView, PostsListView)


app_name = 'feed'

urlpatterns = [
    path('posts', PostsListView.as_view(), name='posts'),
    path('add_ticket_and_review/', CreateTicketAndReviewView.as_view(), name='add_ticket_and_review'),
    path('feed/', FeedView.as_view(), name='feed'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('add_follow/', add_follow, name='add_follow'),
    path('add_ticket/', TicketCreateView.as_view(), name='add_ticket'),
    path('edit_ticket/<int:pk>/', TicketUpdateView.as_view(), name='edit_ticket'),
    path('delete_ticket/<int:pk>/', TicketDeleteView.as_view(), name='delete_ticket'),
    path('add_review/<int:pk>/', ReviewCreateView.as_view(), name='add_review'),
    path('edit_review/<int:pk>/', ReviewUpdateView.as_view(), name='edit_review'),
    path('delete_review/<int:pk>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('follows/', UserFollowsCreateView.as_view(), name='follow_list'),
    path('unfollow/<int:pk>/', unfollowView.as_view(), name='unfollow'),
]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5/dist/litera/bootstrap.min.css" rel="stylesheet">
    <!-- Inclure Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    


    <title>{% block title %}LITRevu{% endblock %}</title>
</head>
<body>
    <div class="container mt-5">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'feed:feed' %}">
                    <img src="{% static 'images/logo.jpeg' %}" alt="Logo" width="50" height="50">
                    LITRevu
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'feed:feed' %}">Mon Flux</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'feed:posts' %}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'feed:follow_list' %}">Abonnements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">
                                {{ user.username }} |
                                <img src="{% static 'images/avatar.png' %}" alt="Avatar" width="30" height="30">
                            </a>
                        </li>
                        <li class="nav-item">
                            {% if user.profile %}
                            <!-- Lien vers le profil si déjà existant -->
                            <a class="nav-link" href="{% url 'accounts:profile_detail' %}">Mon Profil</a>
                            {% else %}
                            <!-- Lien pour créer le profil si inexistant -->
                            <a class="nav-link" href="{% url 'accounts:profile_create' %}">Créer mon Profil</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}"> Déconnexion</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Connexion</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        
        
        

        <main>
            {% block content %}{% endblock %}
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    
    
      

</body>
<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
        <span class="text-muted">© 2024 LITReview</span>
    </div>
</footer>

</html>