src/WebDjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

from rest_framework_simplejwt.views import (
    TokenObtainPairView, 
    TokenRefreshView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('feed/', include('feed.urls', namespace='feed')),
    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False)),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path, include
from .views import signup, logout_view, login_view, ProfileDetailView, ProfileUpdateView, ProfileCreateView, ProfileApiViewSet, UserViewSet
from rest_framework.routers import DefaultRouter



app_name = 'accounts'

router = DefaultRouter()
router.register(r'profiles', ProfileApiViewSet, basename='profile')
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    path('', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('profile/', ProfileDetailView.as_view(), name='profile_detail'),  # Page de consultation du profil
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),  # Page de modification du profil
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('api/', include(router.urls)),
]

src/feed/urls.py
from django.urls import path
from .views import (TicketCreateView, TicketUpdateView,
                    TicketDeleteView, ReviewCreateView, ReviewUpdateView,
                    ReviewDeleteView, UserFollowsCreateView, unfollowView,
                    add_follow, FeedView, TicketDetailView, CreateTicketAndReviewView, PostsListView)


app_name = 'feed'

urlpatterns = [
    path('posts', PostsListView.as_view(), name='posts'),
    path('add_ticket_and_review/', CreateTicketAndReviewView.as_view(), name='add_ticket_and_review'),
    path('feed/', FeedView.as_view(), name='feed'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('add_follow/', add_follow, name='add_follow'),
    path('add_ticket/', TicketCreateView.as_view(), name='add_ticket'),
    path('edit_ticket/<int:pk>/', TicketUpdateView.as_view(), name='edit_ticket'),
    path('delete_ticket/<int:pk>/', TicketDeleteView.as_view(), name='delete_ticket'),
    path('add_review/<int:pk>/', ReviewCreateView.as_view(), name='add_review'),
    path('edit_review/<int:pk>/', ReviewUpdateView.as_view(), name='edit_review'),
    path('delete_review/<int:pk>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('follows/', UserFollowsCreateView.as_view(), name='follow_list'),
    path('unfollow/<int:pk>/', unfollowView.as_view(), name='unfollow'),
]

src/accounts/views.py
# accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Profile
from django.contrib.auth import get_user_model
from .forms import SignUpForm, LoginForm, ProfileForm
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from rest_framework.viewsets import ModelViewSet
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from .serializers import ProfileSerializer, UserSerializer

User = get_user_model()

class AdminOnlyViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = ProfileSerializer

    def get_permissions(self):
        if self.action in ['create', 'update', 'partial_update', 'destroy']:
            return [IsAdminUser()]
        return [IsAuthenticated()]


# Vue pour afficher tous les utilisateurs avec leur profil
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()  # Récupère tous les utilisateurs
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]  # Permission pour accéder à la liste des utilisateurs

# Vue API pour lister les profils utilisateurs
class ProfileApiViewSet(ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = [IsAuthenticated]  # Permission pour accéder à la liste des profils


# Vue pour créer un nouveau profil utilisateur
class ProfileCreateView(LoginRequiredMixin, CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'accounts/profile_create.html'
    success_url = reverse_lazy('accounts:profile_detail')

    def form_valid(self, form):
        # Associer le profil à l'utilisateur connecté
        form.instance.user = self.request.user
        return super().form_valid(form)
    

# Vue pour afficher le profil de l'utilisateur
class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile_detail.html'
    context_object_name = 'profile'

    def get_object(self):
        # Si l'utilisateur n'a pas de profil, rediriger vers la création de profil
        if not hasattr(self.request.user, 'profile'):
            return redirect('accounts:profile_create')
        return self.request.user.profile

# Vue pour mettre à jour le profil de l'utilisateur
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'accounts/profile_edit.html'
    success_url = reverse_lazy('accounts:profile_detail')

    def get_object(self):
        # Récupérer le profil de l'utilisateur connecté
        return self.request.user.profile



def login_view(request):
    """View function for handling user login."""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('feed:feed')  # Redirection mise à jour
            else:
                form.add_error(None, "Nom d'utilisateur ou mot de passe incorrect.")
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    """View function for handling user logout."""
    auth_logout(request)
    return redirect('accounts:login')


def signup(request):
    """View function for handling user signup."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('feed:feed')  # Redirection mise à jour

    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

src/feed/views.py
# feed/views.py
from django.db.models import Q, Prefetch, Count, Value, CharField, F
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse, reverse_lazy
from .models import Ticket, Review, UserFollows
from .forms import UserFollowForm, ReviewForm, TicketForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from itertools import chain


User = get_user_model()


class CreateTicketAndReviewView(LoginRequiredMixin, CreateView):
    """View for creating a ticket and a review."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/create_ticket_and_review.html'

    def form_valid(self, form):
        # Assigner l'utilisateur avant de sauvegarder le formulaire du billet
        form.instance.user = self.request.user
        response = super().form_valid(form)
        # Traiter le formulaire de critique si le billet est validement créé
        review_form = ReviewForm(self.request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.ticket = self.object  # Le nouveau billet créé
            review.user = self.request.user
            review.save()
        return response

    def get_success_url(self):
        """Return the URL to redirect to after creating a ticket and a review."""
        return reverse('feed:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'review_form' not in context:
            context['review_form'] = ReviewForm(self.request.POST or None)
        return context


class TicketDetailView(LoginRequiredMixin, DetailView):
    """View for see a single ticket with all the reviews."""
    model = Ticket
    template_name = 'feed/ticket_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = self.object.review_set.all().order_by('-time_created')
        context['stars'] = range(1, 6)
        return context


class FeedView(LoginRequiredMixin, ListView):
    """View for the feed."""
    template_name = 'feed/feed.html'
    context_object_name = 'feed_items'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        followed_users = UserFollows.objects.filter(user=user).values_list('followed_user', flat=True)
        recent_reviews_prefetch = Prefetch(
            'review_set',
            queryset=Review.objects.order_by('-time_created')[:2],
            to_attr='recent_reviews'
        )
        tickets = Ticket.objects.filter(
            Q(user__in=followed_users) | Q(user=user)
        ).prefetch_related(recent_reviews_prefetch).annotate(num_reviews=Count('review')).order_by('-time_created')
        return tickets

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stars'] = range(1, 6)
        return context


@login_required
def add_follow(request):
    """add a follow."""
    if request.method == 'POST':
        form = UserFollowForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                followed_user = User.objects.get(username=username)
                if UserFollows.objects.filter(user=request.user, followed_user=followed_user).exists():
                    form.add_error(None, 'Vous suivez déjà cet utilisateur.')
                else:
                    UserFollows.objects.create(user=request.user, followed_user=followed_user)
                    return redirect('feed:follow_list')
            except User.DoesNotExist:
                form.add_error('username', 'Cet utilisateur n\'existe pas.')
    else:
        form = UserFollowForm()
    return render(request, 'feed/add_follow.html', {'form': form})


class UserFollowsCreateView(LoginRequiredMixin, ListView):
    """View for following a user."""
    model = UserFollows
    template_name = 'feed/user_follows.html'
    context_object_name = 'follows'

    def get_queryset(self):
        return UserFollows.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserFollowForm()
        context['followers'] = UserFollows.objects.filter(followed_user=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        form = UserFollowForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                followed_user = User.objects.get(username=username)
                if UserFollows.objects.filter(user=request.user, followed_user=followed_user).exists():
                    messages.error(request, 'Vous suivez déjà cet utilisateur.')
                else:
                    UserFollows.objects.create(user=request.user, followed_user=followed_user)
                    messages.success(request, 'Utilisateur suivi avec succès.')
                    return redirect('feed:follow_list')
            except User.DoesNotExist:
                messages.error(request, 'Cet utilisateur n\'existe pas.')
        else:
            # Gestion des erreurs du formulaire
            for error in form.errors.values():
                messages.error(request, error.as_text())
        return super().get(request, *args, **kwargs)  # Rediriger vers la même page avec les messages d'erreur.


class unfollowView(LoginRequiredMixin, DeleteView):
    model = UserFollows
    success_url = reverse_lazy('feed:follow_list')

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """View for creating a review."""
    model = Review
    form_class = ReviewForm
    template_name = 'feed/review_create_form.html'

    def form_valid(self, form):
        # Vérification pour éviter la duplication de critique pour le même ticket par le même utilisateur
        self.ticket = get_object_or_404(Ticket, pk=self.kwargs.get('pk'))
        existing_review = Review.objects.filter(ticket=self.ticket, user=self.request.user).exists()
        if existing_review:
            form.add_error(None, 'Vous avez déjà publié une critique pour ce billet.')
            form.add_error(None, 'Cliquez pour retourner au flux.')
            return self.form_invalid(form)

        form.instance.user = self.request.user
        form.instance.ticket = self.ticket
        return super().form_valid(form)

    def get_success_url(self):
        """Return the URL to redirect to after creating a review."""
        return reverse('feed:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket'] = get_object_or_404(Ticket, pk=self.kwargs.get('pk'))
        return context


class ReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """View for updating a review"""
    model = Review
    form_class = ReviewForm
    template_name = 'feed/review_update_form.html'

    def test_func(self):
        # Récupère l'objet review en cours de modification
        review = self.get_object()
        # Vérifie que l'utilisateur actuel est l'auteur de la critique
        return self.request.user == review.user

    def get_queryset(self):
        """Return the reviews of the current user."""
        return Review.objects.filter(user=self.request.user)

    def get_success_url(self):
        """Return the URL to redirect to after updating a review."""
        return reverse('feed:posts')


class ReviewDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View for deleting a review."""
    model = Review
    template_name = 'feed/review_confirm_delete.html'

    def test_func(self):
        # Récupère l'objet review en cours de modification
        review = self.get_object()
        # Vérifie que l'utilisateur actuel est l'auteur de la critique
        return self.request.user == review.user

    def get_queryset(self):
        """Return the reviews of the current user."""
        return Review.objects.filter(user=self.request.user)

    def get_success_url(self):
        """Return the URL to redirect to after deleting a review."""
        return reverse('feed:posts')


class TicketCreateView(LoginRequiredMixin, CreateView):
    """View for creating a ticket."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/ticket_create.html'
    success_url = reverse_lazy('feed:feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """View for updating a ticket."""
    model = Ticket
    form_class = TicketForm
    template_name = 'feed/ticket_update_form.html'
    success_url = reverse_lazy('feed:posts')

    def test_func(self):
        ticket = self.get_object()
        return ticket.user == self.request.user


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View for deleting a ticket."""
    model = Ticket
    template_name = 'feed/ticket_confirm_delete.html'
    success_url = reverse_lazy('feed:posts')

    def test_func(self):
        ticket = self.get_object()
        return ticket.user == self.request.user


class PostsListView(LoginRequiredMixin, ListView):
    """View for listing tickets and reviews."""
    template_name = 'feed/posts_list.html'
    context_object_name = 'items'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user

src/accounts/templates/accounts/feed.html
<!-- templates/accounts/feed.html -->
{% extends 'base.html' %}

{% block title %}Feed{% endblock %}

{% block content %}
<h1>Bienvenue sur le flux de LITReview</h1>
<p><a href="{% url 'accounts:logout' %}">Déconnectez-vous</a></p>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Connectez-vous ou Inscrivez-vous{% endblock %}




{% block content %}

</br></br></br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" class="login-form">
            <div class="card-group mb-0">
                <!-- Connexion -->
                <div class="card p-4">
                    <div class="card-body">
                        <h2 style="text-align: center;">Connectez-vous</h2>
                        <p class="text-muted">Connectez-vous avec votre compte</p>
                        <form method="post" action="{% url 'accounts:login' %}" id="login-form">
                            {% csrf_token %}
                            <!-- Affichage du message d'erreur général -->
                            {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                           {% endif %}
                           
                            <!-- Champs de formulaire avec form-floating -->
                            <div class="input-group mb-3">
                                <label for="username" class="sr-only">Nom d'utilisateur</label>
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <input type="text" class="form-control" placeholder="Username" name="username">
                            </div>
                            <div class="input-group mb-4">
                                <label for="password" class="sr-only">Mot de passe</label>
                                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                <input type="password" class="form-control" placeholder="Password" name="password">
                            <!-- Affichage des erreurs pour le champ password -->
                            
                            
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <button type="submit" class="btn btn-primary px-4">Connexion</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Inscription -->
                <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
                    <div class="card-body text-center">
                        <div>
                            <h2>Inscrivez-vous</h2>
                            <p>Vous n'avez pas de compte? Inscrivez-vous maintenant!</p>
                            <a href="{% url 'accounts:signup' %}" class="btn btn-primary active mt-3">S'inscrire</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('signup-form').onsubmit = function() {
        this.reset();  // Reset all form fields to their initial values
    };
</script>


{% endblock %}

src/accounts/templates/accounts/profile_create.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Créer votre profil</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Créer le profil</button>
    </form>
</div>
{% endblock %}

src/accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Votre profil</h1>
    <p><strong>Nom d'utilisateur :</strong> {{ profile.user.username }}</p>
    <p><strong>Email :</strong> {{ profile.user.email }}</p>
    <p><strong>Biographie :</strong> {{ profile.bio|default:"Pas de biographie." }}</p>
    <p><strong>Photo de profil :</strong></p>
    {% if profile.avatar %}
        <img src="{{ profile.avatar.url }}" alt="Photo de profil" style="max-width: 200px;">
    {% else %}
        <p>Aucune photo de profil.</p>
    {% endif %}
    <a href="{% url 'accounts:profile_edit' %}" class="btn btn-primary">Modifier le profil</a>
</div>
{% endblock %}

src/accounts/templates/accounts/profile_edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Modifier votre profil</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</div>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
</br></br></br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" class="login-form">
            <div class="card-group mb-0">
                <!-- Inscription -->
                <div class="card p-4">
                    <div class="card-body">
                        <h2 style="text-align: center;">Inscrivez-vous</h2>
                        <p class="text-muted">Créez votre compte</p>
                        <form method="post" id="signup-form">
                            {% csrf_token %}
                            <!-- Affichage du message d'erreur général -->
                            {% if form.errors %}
                            <div class="alert alert-danger">
                               
                               
                                <p>{{ form.errors }}</p>
                                    
                                   
                               
                            </div>
                            {% endif %}
                            <!-- Champs de formulaire avec form-floating -->
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="id_username" name="username" placeholder="Nom d'utilisateur" required>
                                
                                <label for="id_username">Nom d'utilisateur</label>
                                
                                

                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Mot de passe" required>
                                <label for="id_password1">Mot de passe</label>
                               
                                
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Confirmez le mot de passe" required>
                                <label for="id_password2">Confirmez le mot de passe</label>
                                
                                
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <button type="submit" class="btn btn-primary px-4">S'inscrire</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Lien de retour à la connexion -->
                <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
                    <div class="card-body text-center">
                        <div>
                            <h2>Connectez-vous</h2>
                            <p>Déjà inscrit? Connectez-vous ici!</p>
                            <a href="{% url 'accounts:login' %}" class="btn btn-primary active mt-3">Connexion</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('signup-form').onsubmit = function() {
        // this.reset();  // Reset all form fields to their initial values
    };
</script>
{% endblock %}